### PR TITLE
Fixed stdout when lines are cleared

### PR DESCRIPTION
**Pull request by aecz**
Some ANSI code are not well processed like those that clear the entire line or move the cursor around.
Still need to support moving the cursor to far left as its conflicting with the coloredPrefix.
https://en.wikipedia.org/wiki/ANSI_escape_code

### CODE REVIEW

**Comment by kimmobrunfeldt** [comment]
Could you provide an example what is incorrect behaviour and how this fixes it. I might be just too tired but I didn't yet get the problem this PR solves, thanks.

**Comment by aecz** [comment]
Here is some steps to reproduce the issue:
```
git clone https://github.com/callemall/material-ui-webpack-example.git
cd material-ui-webpack-example
npm i
npm i concurrently
node_modules/.bin/concurrently "npm start"
```
Comparing the output with "npm start", we can see that many lines are not cleared but added. This is due to manually adding a line break to stdout when we should instead let the process add them.

**Comment by aaronjensen** [comment]
@gustavohenke thanks for merging this, this cleans up the output for us quite a bit. If you get a chance could you please release a new version? We're happy to pull from git from now, but a new version would be great. Thanks! /cc @kimmobrunfeldt

**Comment by gustavohenke** [comment]
Sure! I should have done this before. v3.5.1 is on its way! 🚢

**Pull request merged**
