### PR TITLE
Support for hex colors in prefixColor #260

### LINKED ISSUE #260: Add support to pass hex colors in prefixColor
Hex colors are not currently supported as `prefixColor` value. However `chalk` package which is used internally has support for hex colors. It should be fixed by the following code?

```js
let color;
if(command.prefixColor.startsWith("#")) {
  color = chalk.hex(command.prefixColor)
} else {
  color = _.get(chalk, command.prefixColor, chalk.gray.dim);
}
```

Happy to open a PR!

### PR DESCRIPTION
**Pull request by rramaa**
This fixes #260

### CODE REVIEW

**Comment by rramaa** [comment]
@gustavohenke It would be awesome if you could review this and release it!
Thanks

**Review by gustavohenke — CHANGES_REQUESTED** [review]
So nice, thanks!

Can you also add a brief information to here, please?
https://github.com/kimmobrunfeldt/concurrently/blob/2e1ad013896f91c1e15386fdd94e769c83ae45c9/bin/concurrently.js#L80-L88

**Comment by rramaa** [comment]
@gustavohenke done

**Review by gustavohenke — APPROVED** [review]

**Comment by gustavohenke** [comment]
Out in v6.0.0, thanks!

**Pull request merged**
