### PR TITLE
Fix for nested concurrently --kill-others for MAC and windows fix for…

### PR DESCRIPTION
**Pull request by daniloster**
… the other open PR

Please, evaluate it and merge as soon as possible. I need that fix and it is related to the SIGTERM issue open and the windows fix PR open but not merged. Btw, thanks for creating this library. It is awesome. ;)

### CODE REVIEW

**Comment by daniloster** [comment]
@niieani could you check if it is fine for you as well? Thanks!

**Comment by danilosterrapid7** [comment]
@filipesilva could you check if it is fine for you as well? Thanks!

**Comment by kimmobrunfeldt** [comment]
If others could confirm this works, I can merge and release it. Sorry I don't have time to test it.

**Comment by danilosterrapid7** [comment]
Definitely, this fix the problem on mac osx cause I tested it. I just need confirmation for windows version.

**Comment by filipesilva** [comment]
@daniloster @kimmobrunfeldt can confirm it works for windows :D
```
kamik@T460p MINGW64 /D/sandbox/concurrently (pr/39)
$ concurrently "hs" "echo 'hello'" --kill-others
[1] 'hello'
[1] echo 'hello' exited with code 0
[0] Starting up http-server, serving ./
[0] Available on:
[0]   http://192.168.0.17:8080
[0]   http://127.0.0.1:8080
[0] Hit CTRL-C to stop the server
--> Sending SIGTERM to other processes..
[0] hs exited with code 1
```

**Comment by niieani** [comment]
Did anybody test if it fixes the issue on Linux? I can't test right now.

**Comment by danilosterrapid7** [comment]
I've just tested on Mac osx!

**Comment by danilosterrapid7** [comment]
Could someone please test on Linux environment? Thanks!

**Comment by danilosterrapid7** [comment]
@niieani could you test it on Linux, please? 😃

**Comment by niieani** [comment]
@danilosterrapid7 it's on my todo. I'll try to today.

**Comment by danilosterrapid7** [comment]
I have just run the tests on Linux and they've passed! I think it is good to go.
@kimmobrunfeldt @filipesilva @niieani

**Comment by danilosterrapid7** [comment]
image

**Comment by kimmobrunfeldt** [comment]
Now released as 2.2.0 https://github.com/kimmobrunfeldt/concurrently/releases/tag/2.2.0
Thanks for everyone

**Comment by marcioj** [comment]
Unfortunately this change just works for me if I change `child.kill('SIGINT');` to `child.kill('SIGTERM');`.
Does make sense to trigger both signals or use a more aggressive signal?

**Comment by daniloster** [comment]
Havd you tried to send both signals, @marcioj?

**Pull request merged**
