### PR TITLE
Propagate SIGTERM and SIGINT to child processes

### PR DESCRIPTION
**Pull request by julienw**

### CODE REVIEW

**Comment by kimmobrunfeldt** [comment]
Looks good to me, anything to consider before releasing?

**Comment by julienw** [comment]
Hey,

Honestly I think this would just work :)

**Comment by julienw** [comment]
any update ?

**Comment by kimmobrunfeldt** [comment]
Could you test if this has been fixed by installing 3.0.0-dev version: `npm i -g concurrently@3.0.0-dev` ?

**Pull request merged**
